In [1]:
import pandas as pd
import os
import detect_simpsons_paradox as dsp
import numpy as np

In [2]:
hit_search_rate = pd.read_csv('../data/state_hit_rate_min_cols_COCTFLILMDMAMOMTNENCOHRISCTXVTWAWI.csv',index_col='Unnamed: 0')
hit_search_rate.head()

state  year driver_gender driver_race  decriminalization  medical  \
0    AZ  2009             F       White                  0        0   
1    AZ  2009             M       Black                  0        0   
2    AZ  2009             M    Hispanic                  0        0   
3    AZ  2009             M       White                  0        0   
4    AZ  2010             F       Asian                  0        1   

   recreational  no_reforms  search_conducted_false  search_conducted_true  \
0             0           1                    30.0                    1.0   
1             0           1                     1.0                    2.0   
2             0           1                    14.0                    1.0   
3             0           1                    32.0                    4.0   
4             0           0                    58.0                    3.0   

   search_conducted_rate  contraband_found_false  contraband_found_true  \
0               0.032258                    31.0                    NaN   
1               0.666667                     2.0                    1.0   
2               0.066667                    15.0                    NaN   
3               0.111111                    34.0                    2.0   
4               0.049180                    61.0                    NaN   

   contraband_found_rate  hit_false  hit_true  hit_rate  num_stops  
0                    NaN        1.0       NaN       NaN       31.0  
1               0.333333        1.0       1.0       0.5        3.0  
2                    NaN        1.0       NaN       NaN       15.0  
3               0.055556        2.0       2.0       0.5       36.0  
4                    NaN        3.0       NaN       NaN       61.0

In [3]:
labeled_df = dsp.labeledDataFrame(hit_search_rate)

In [4]:
labeled_df.infer_var_types()
labeled_df.meta_df.index

Index(['state', 'year', 'driver_gender', 'driver_race', 'decriminalization',
       'medical', 'recreational', 'no_reforms', 'search_conducted_false',
       'search_conducted_true', 'search_conducted_rate',
       'contraband_found_false', 'contraband_found_true',
       'contraband_found_rate', 'hit_false', 'hit_true', 'hit_rate',
       'num_stops'],
      dtype='object')

In [5]:
labeled_df.meta_df.head()

dtype     var_type role isCount count_of
state              object  categorical  NaN     NaN      NaN
year                int64      ordinal  NaN     NaN      NaN
driver_gender      object       binary  NaN     NaN      NaN
driver_race        object  categorical  NaN     NaN      NaN
decriminalization   int64       binary  NaN     NaN      NaN

In [6]:
roles = {'state':'trend', 'year':'trend', 'driver_gender':['explanatory','groupby'], 'driver_race':['explanatory','groupby'],
       'decriminalization':['explanatory','groupby'], 'medical':['explanatory','groupby'],
         'recreational':['explanatory','groupby'], 'no_reforms':['explanatory','groupby'],
       'search_conducted_false':'trend', 'search_conducted_true':'trend',
       'search_conducted_rate':'trend', 'contraband_found_false':'trend',
       'contraband_found_true':'trend', 'contraband_found_rate':'trend', 'hit_false':'trend',
       'hit_true':'trend', 'hit_rate':'trend', 'num_stops':'trend'}
is_count = {'state':False, 'year':False, 'driver_gender':False, 'driver_race':False,
       'decriminalization':False, 'medical':False, 'recreational':False, 'no_reforms':False,
       'search_conducted_false':True, 'search_conducted_true':True,
       'search_conducted_rate':False, 'contraband_found_false':True,
       'contraband_found_true':True, 'contraband_found_rate':False, 'hit_false':True,
       'hit_true':True, 'hit_rate':False, 'num_stops':True}
count_list = ['search_conducted_false', 'search_conducted_true','contraband_found_false',
       'contraband_found_true', 'hit_false',
       'hit_true', 'num_stops']

In [7]:
meta_df = labeled_df.meta_df

meta_df.loc['search_conducted_false','isCount']

nan

In [8]:
labeled_df.set_counts(count_list)
labeled_df.meta_df.head()

dtype     var_type role  isCount count_of
state              object  categorical  NaN    False      NaN
year                int64      ordinal  NaN    False      NaN
driver_gender      object       binary  NaN    False      NaN
driver_race        object  categorical  NaN    False      NaN
decriminalization   int64       binary  NaN    False      NaN

In [9]:
labeled_df.set_roles(roles)
labeled_df.meta_df

/home/smb/anaconda3/lib/python3.6/site-packages/detect_simpsons_paradox/labeled_dataframe.py:143: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.meta_df['role'][k] = v


dtype     var_type                    role  isCount  \
state                    object  categorical                   trend    False   
year                      int64      ordinal                   trend    False   
driver_gender            object       binary  [explanatory, groupby]    False   
driver_race              object  categorical  [explanatory, groupby]    False   
decriminalization         int64       binary  [explanatory, groupby]    False   
medical                   int64       binary  [explanatory, groupby]    False   
recreational              int64       binary  [explanatory, groupby]    False   
no_reforms                int64       binary  [explanatory, groupby]    False   
search_conducted_false  float64   continuous                   trend     True   
search_conducted_true   float64   continuous                   trend     True   
search_conducted_rate   float64   continuous                   trend    False   
contraband_found_false  float64   continuous                   trend     True   
contraband_found_true   float64   continuous                   trend     True   
contraband_found_rate   float64   continuous                   trend    False   
hit_false               float64   continuous                   trend     True   
hit_true                float64   continuous                   trend     True   
hit_rate                float64   continuous                   trend    False   
num_stops               float64   continuous                   trend     True   

                       count_of  
state                       NaN  
year                        NaN  
driver_gender               NaN  
driver_race                 NaN  
decriminalization           NaN  
medical                     NaN  
recreational                NaN  
no_reforms                  NaN  
search_conducted_false      NaN  
search_conducted_true       NaN  
search_conducted_rate       NaN  
contraband_found_false      NaN  
contraband_found_true       NaN  
contraband_found_rate       NaN  
hit_false                   NaN  
hit_true                    NaN  
hit_rate                    NaN  
num_stops                   NaN

In [10]:
labeled_df.get_vars_per_role('groupby')

Index(['driver_gender', 'driver_race', 'decriminalization', 'medical',
       'recreational', 'no_reforms'],
      dtype='object')

In [11]:
corrobj = dsp.correlation_trend()
corrobj.get_trend_vars(labeled_df)
corrobj.regression_vars

Index(['search_conducted_false', 'search_conducted_true',
       'search_conducted_rate', 'contraband_found_false',
       'contraband_found_true', 'contraband_found_rate', 'hit_false',
       'hit_true', 'hit_rate', 'num_stops'],
      dtype='object')

In [12]:
len(corrobj.regression_vars)

10

In [13]:
(labeled_df.df[corrobj.regression_vars].corr()).shape

(10, 10)

In [16]:
labeled_df.get_subgroup_trends_1lev([corrobj])

10
reg
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7,
       8]), array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7,
       8, 9, 4, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 6, 7, 8, 9, 7, 8, 9, 8, 9,
       9]))
10
gby
(array([ 0, 10,  0, 10,  0, 10,  0, 10,  0, 10,  0, 10,  0, 10,  0, 10,  0,
       10,  1, 11,  1, 11,  1, 11,  1, 11,  1, 11,  1, 11,  1, 11,  1, 11,
        2, 12,  2, 12,  2, 12,  2, 12,  2, 12,  2, 12,  2, 12,  3, 13,  3,
       13,  3, 13,  3, 13,  3, 13,  3, 13,  4, 14,  4, 14,  4, 14,  4, 14,
        4, 14,  5, 15,  5, 15,  5, 15,  5, 15,  6, 16,  6, 16,  6, 16,  7,
       17,  7, 17,  8, 18]), array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 2, 2, 3, 3,
       4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7,
       8, 8, 9, 9, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 5, 5, 6, 6, 7, 7,
       8, 8, 9, 9, 6, 6, 7, 7, 8, 8, 9, 9, 7,

feat1                  feat2  subgroup_trend  \
0    search_conducted_false  search_conducted_true        0.874650   
1    search_conducted_false  search_conducted_true        0.890130   
2    search_conducted_false  search_conducted_true        0.891302   
3    search_conducted_false  search_conducted_true        0.743555   
4    search_conducted_false  search_conducted_true        0.886433   
5    search_conducted_false  search_conducted_true        0.688787   
6    search_conducted_false  search_conducted_true        0.883648   
7    search_conducted_false  search_conducted_true        0.894280   
8    search_conducted_false  search_conducted_true        0.882396   
9    search_conducted_false  search_conducted_true        0.872176   
10   search_conducted_false  search_conducted_true        0.868391   
11   search_conducted_false  search_conducted_true        0.868577   
12   search_conducted_false  search_conducted_true        0.898105   
13   search_conducted_false  search_conducted_true        0.876102   
14   search_conducted_false  search_conducted_true        0.847307   
15   search_conducted_false  search_conducted_rate       -0.141186   
16   search_conducted_false  search_conducted_rate       -0.105610   
17   search_conducted_false  search_conducted_rate        0.253146   
18   search_conducted_false  search_conducted_rate       -0.146583   
19   search_conducted_false  search_conducted_rate       -0.070255   
20   search_conducted_false  search_conducted_rate        0.035903   
21   search_conducted_false  search_conducted_rate        0.071893   
22   search_conducted_false  search_conducted_rate       -0.095882   
23   search_conducted_false  search_conducted_rate        0.074504   
24   search_conducted_false  search_conducted_rate       -0.060908   
25   search_conducted_false  search_conducted_rate       -0.052758   
26   search_conducted_false  search_conducted_rate       -0.073649   
27   search_conducted_false  search_conducted_rate       -0.009705   
28   search_conducted_false  search_conducted_rate       -0.055616   
29   search_conducted_false  search_conducted_rate       -0.128267   
..                      ...                    ...             ...   
645                hit_true              num_stops        0.904561   
646                hit_true              num_stops        0.906331   
647                hit_true              num_stops        0.827854   
648                hit_true              num_stops        0.765859   
649                hit_true              num_stops        0.941027   
650                hit_true              num_stops        0.690273   
651                hit_true              num_stops        0.889423   
652                hit_true              num_stops        0.848768   
653                hit_true              num_stops        0.898839   
654                hit_true              num_stops        0.893317   
655                hit_true              num_stops        0.826921   
656                hit_true              num_stops        0.896665   
657                hit_true              num_stops        0.842123   
658                hit_true              num_stops        0.890201   
659                hit_true              num_stops        0.868256   
660                hit_rate              num_stops       -0.048772   
661                hit_rate              num_stops       -0.049530   
662                hit_rate              num_stops       -0.264280   
663                hit_rate              num_stops       -0.221334   
664                hit_rate              num_stops       -0.085910   
665                hit_rate              num_stops       -0.329973   
666                hit_rate              num_stops       -0.251534   
667                hit_rate              num_stops       -0.082519   
668                hit_rate              num_stops       -0.084309   
669                hit_rate              num_stops        0.033867   
670                hit_rate     

In [15]:
np.triu_indices(12,k=1)

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,
         3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,
         6,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  9,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  2,  3,  4,  5,  6,  7,
         8,  9, 10, 11,  3,  4,  5,  6,  7,  8,  9, 10, 11,  4,  5,  6,  7,
         8,  9, 10, 11,  5,  6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11,
         7,  8,  9, 10, 11,  8,  9, 10, 11,  9, 10, 11, 10, 11, 11]))